// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace opamp.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AnyValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"string_value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StringValue
        {
            get => __pbn__value.Is(1) ? ((string)__pbn__value.Object) : "";
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(1, value);
        }
        public bool ShouldSerializeStringValue() => __pbn__value.Is(1);
        public void ResetStringValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__value;

        [global::ProtoBuf.ProtoMember(2, Name = @"bool_value")]
        public bool BoolValue
        {
            get => __pbn__value.Is(2) ? __pbn__value.Boolean : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeBoolValue() => __pbn__value.Is(2);
        public void ResetBoolValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"int_value")]
        public long IntValue
        {
            get => __pbn__value.Is(3) ? __pbn__value.Int64 : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeIntValue() => __pbn__value.Is(3);
        public void ResetIntValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"double_value")]
        public double DoubleValue
        {
            get => __pbn__value.Is(4) ? __pbn__value.Double : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(4, value);
        }
        public bool ShouldSerializeDoubleValue() => __pbn__value.Is(4);
        public void ResetDoubleValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"array_value")]
        public ArrayValue ArrayValue
        {
            get => __pbn__value.Is(5) ? ((ArrayValue)__pbn__value.Object) : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(5, value);
        }
        public bool ShouldSerializeArrayValue() => __pbn__value.Is(5);
        public void ResetArrayValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"kvlist_value")]
        public KeyValueList KvlistValue
        {
            get => __pbn__value.Is(6) ? ((KeyValueList)__pbn__value.Object) : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(6, value);
        }
        public bool ShouldSerializeKvlistValue() => __pbn__value.Is(6);
        public void ResetKvlistValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"bytes_value")]
        public byte[] BytesValue
        {
            get => __pbn__value.Is(7) ? ((byte[])__pbn__value.Object) : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(7, value);
        }
        public bool ShouldSerializeBytesValue() => __pbn__value.Is(7);
        public void ResetBytesValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 7);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArrayValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"values")]
        public global::System.Collections.Generic.List<AnyValue> Values { get; } = new global::System.Collections.Generic.List<AnyValue>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyValueList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"values")]
        public global::System.Collections.Generic.List<KeyValue> Values { get; } = new global::System.Collections.Generic.List<KeyValue>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public AnyValue Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentToServer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"instance_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InstanceUid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"sequence_num")]
        public ulong SequenceNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"agent_description")]
        public AgentDescription AgentDescription { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"capabilities")]
        public ulong Capabilities { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"health")]
        public ComponentHealth Health { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"effective_config")]
        public EffectiveConfig EffectiveConfig { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"remote_config_status")]
        public RemoteConfigStatus RemoteConfigStatus { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"package_statuses")]
        public PackageStatuses PackageStatuses { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"agent_disconnect")]
        public AgentDisconnect AgentDisconnect { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"flags")]
        public ulong Flags { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"connection_settings_request")]
        public ConnectionSettingsRequest ConnectionSettingsRequest { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"custom_capabilities")]
        public CustomCapabilities CustomCapabilities { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"custom_message")]
        public CustomMessage CustomMessage { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentDisconnect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectionSettingsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opamp")]
        public OpAMPConnectionSettingsRequest Opamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpAMPConnectionSettingsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"certificate_request")]
        public CertificateRequest CertificateRequest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CertificateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"csr")]
        public byte[] Csr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerToAgent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"instance_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InstanceUid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"error_response")]
        public ServerErrorResponse ErrorResponse { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"remote_config")]
        public AgentRemoteConfig RemoteConfig { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"connection_settings")]
        public ConnectionSettingsOffers ConnectionSettings { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"packages_available")]
        public PackagesAvailable PackagesAvailable { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"flags")]
        public ulong Flags { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"capabilities")]
        public ulong Capabilities { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"agent_identification")]
        public AgentIdentification AgentIdentification { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"command")]
        public ServerToAgentCommand Command { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"custom_capabilities")]
        public CustomCapabilities CustomCapabilities { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"custom_message")]
        public CustomMessage CustomMessage { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpAMPConnectionSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination_endpoint")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DestinationEndpoint { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"headers")]
        public Headers Headers { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"certificate")]
        public TLSCertificate Certificate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TelemetryConnectionSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination_endpoint")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DestinationEndpoint { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"headers")]
        public Headers Headers { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"certificate")]
        public TLSCertificate Certificate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OtherConnectionSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination_endpoint")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DestinationEndpoint { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"headers")]
        public Headers Headers { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"certificate")]
        public TLSCertificate Certificate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"other_settings")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> OtherSettings { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Headers : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Header> headers { get; } = new global::System.Collections.Generic.List<Header>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Header : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TLSCertificate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"public_key")]
        public byte[] PublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"private_key")]
        public byte[] PrivateKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ca_public_key")]
        public byte[] CaPublicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectionSettingsOffers : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        public byte[] Hash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"opamp")]
        public OpAMPConnectionSettings Opamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"own_metrics")]
        public TelemetryConnectionSettings OwnMetrics { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"own_traces")]
        public TelemetryConnectionSettings OwnTraces { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"own_logs")]
        public TelemetryConnectionSettings OwnLogs { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"other_connections")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, OtherConnectionSettings> OtherConnections { get; } = new global::System.Collections.Generic.Dictionary<string, OtherConnectionSettings>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackagesAvailable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"packages")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, PackageAvailable> Packages { get; } = new global::System.Collections.Generic.Dictionary<string, PackageAvailable>();

        [global::ProtoBuf.ProtoMember(2, Name = @"all_packages_hash")]
        public byte[] AllPackagesHash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackageAvailable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public PackageType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Version { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"file")]
        public DownloadableFile File { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hash")]
        public byte[] Hash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DownloadableFile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"download_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DownloadUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"content_hash")]
        public byte[] ContentHash { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"signature")]
        public byte[] Signature { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerErrorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public ServerErrorResponseType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"retry_info")]
        public RetryInfo RetryInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RetryInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retry_after_nanoseconds")]
        public ulong RetryAfterNanoseconds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerToAgentCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public CommandType Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentDescription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identifying_attributes")]
        public global::System.Collections.Generic.List<KeyValue> IdentifyingAttributes { get; } = new global::System.Collections.Generic.List<KeyValue>();

        [global::ProtoBuf.ProtoMember(2, Name = @"non_identifying_attributes")]
        public global::System.Collections.Generic.List<KeyValue> NonIdentifyingAttributes { get; } = new global::System.Collections.Generic.List<KeyValue>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComponentHealth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"healthy")]
        public bool Healthy { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"start_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"last_error")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LastError { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"status")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Status { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"status_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StatusTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"component_health_map")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, ComponentHealth> ComponentHealthMaps { get; } = new global::System.Collections.Generic.Dictionary<string, ComponentHealth>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EffectiveConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"config_map")]
        public AgentConfigMap ConfigMap { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RemoteConfigStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"last_remote_config_hash")]
        public byte[] LastRemoteConfigHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public RemoteConfigStatuses Status { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackageStatuses : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"packages")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, PackageStatus> Packages { get; } = new global::System.Collections.Generic.Dictionary<string, PackageStatus>();

        [global::ProtoBuf.ProtoMember(2, Name = @"server_provided_all_packages_hash")]
        public byte[] ServerProvidedAllPackagesHash { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackageStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"agent_has_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AgentHasVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"agent_has_hash")]
        public byte[] AgentHasHash { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"server_offered_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServerOfferedVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"server_offered_hash")]
        public byte[] ServerOfferedHash { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"status")]
        public PackageStatusEnum Status { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentIdentification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"new_instance_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewInstanceUid { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentRemoteConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"config")]
        public AgentConfigMap Config { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"config_hash")]
        public byte[] ConfigHash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentConfigMap : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"config_map")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, AgentConfigFile> ConfigMaps { get; } = new global::System.Collections.Generic.Dictionary<string, AgentConfigFile>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentConfigFile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body")]
        public byte[] Body { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"content_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContentType { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomCapabilities : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"capabilities")]
        public global::System.Collections.Generic.List<string> Capabilities { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"capability")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Capability { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AgentToServerFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AgentToServerFlags_Unspecified")]
        AgentToServerFlagsUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentToServerFlags_RequestInstanceUid")]
        AgentToServerFlagsRequestInstanceUid = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ServerToAgentFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ServerToAgentFlags_Unspecified")]
        ServerToAgentFlagsUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerToAgentFlags_ReportFullState")]
        ServerToAgentFlagsReportFullState = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ServerCapabilities
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_Unspecified")]
        ServerCapabilitiesUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_AcceptsStatus")]
        ServerCapabilitiesAcceptsStatus = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_OffersRemoteConfig")]
        ServerCapabilitiesOffersRemoteConfig = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_AcceptsEffectiveConfig")]
        ServerCapabilitiesAcceptsEffectiveConfig = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_OffersPackages")]
        ServerCapabilitiesOffersPackages = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_AcceptsPackagesStatus")]
        ServerCapabilitiesAcceptsPackagesStatus = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_OffersConnectionSettings")]
        ServerCapabilitiesOffersConnectionSettings = 32,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerCapabilities_AcceptsConnectionSettingsRequest")]
        ServerCapabilitiesAcceptsConnectionSettingsRequest = 64,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PackageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PackageType_TopLevel")]
        PackageTypeTopLevel = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PackageType_Addon")]
        PackageTypeAddon = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ServerErrorResponseType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ServerErrorResponseType_Unknown")]
        ServerErrorResponseTypeUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerErrorResponseType_BadRequest")]
        ServerErrorResponseTypeBadRequest = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ServerErrorResponseType_Unavailable")]
        ServerErrorResponseTypeUnavailable = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CommandType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CommandType_Restart")]
        CommandTypeRestart = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AgentCapabilities
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_Unspecified")]
        AgentCapabilitiesUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsStatus")]
        AgentCapabilitiesReportsStatus = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_AcceptsRemoteConfig")]
        AgentCapabilitiesAcceptsRemoteConfig = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsEffectiveConfig")]
        AgentCapabilitiesReportsEffectiveConfig = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_AcceptsPackages")]
        AgentCapabilitiesAcceptsPackages = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsPackageStatuses")]
        AgentCapabilitiesReportsPackageStatuses = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsOwnTraces")]
        AgentCapabilitiesReportsOwnTraces = 32,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsOwnMetrics")]
        AgentCapabilitiesReportsOwnMetrics = 64,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsOwnLogs")]
        AgentCapabilitiesReportsOwnLogs = 128,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_AcceptsOpAMPConnectionSettings")]
        AgentCapabilitiesAcceptsOpAMPConnectionSettings = 256,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_AcceptsOtherConnectionSettings")]
        AgentCapabilitiesAcceptsOtherConnectionSettings = 512,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_AcceptsRestartCommand")]
        AgentCapabilitiesAcceptsRestartCommand = 1024,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsHealth")]
        AgentCapabilitiesReportsHealth = 2048,
        [global::ProtoBuf.ProtoEnum(Name = @"AgentCapabilities_ReportsRemoteConfig")]
        AgentCapabilitiesReportsRemoteConfig = 4096,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RemoteConfigStatuses
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RemoteConfigStatuses_UNSET")]
        RemoteConfigStatusesUNSET = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RemoteConfigStatuses_APPLIED")]
        RemoteConfigStatusesAPPLIED = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"RemoteConfigStatuses_APPLYING")]
        RemoteConfigStatusesAPPLYING = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"RemoteConfigStatuses_FAILED")]
        RemoteConfigStatusesFAILED = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PackageStatusEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PackageStatusEnum_Installed")]
        PackageStatusEnumInstalled = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PackageStatusEnum_InstallPending")]
        PackageStatusEnumInstallPending = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PackageStatusEnum_Installing")]
        PackageStatusEnumInstalling = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PackageStatusEnum_InstallFailed")]
        PackageStatusEnumInstallFailed = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
